# Generated by Django 4.2 on 2023-04-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='FirstName', max_length=255)),
                ('lastname', models.CharField(default='LastName', max_length=255)),
                ('emailid', models.EmailField(default='emailid', max_length=100)),
                ('phonenumber', models.CharField(default='0', max_length=10)),
                ('Description', models.CharField(default='Skills Set', max_length=700)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch.position')),
            ],
        ),
    ]
