# Generated by Django 4.2 on 2023-04-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerefer',
            name='UploadResume',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
