# Generated by Django 4.2 on 2023-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_employeerefer_uploadresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerefer',
            name='Experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeerefer',
            name='Relation',
            field=models.CharField(default='Friend'),
        ),
    ]
